[package]
name = "roper"
version = "0.1.0"
authors = ["oblivia simplex <oblivia@paranoici.org>"]


[dependencies]
unicorn  = { git = "https://github.com/oblivia-simplex/unicorn-rs", branch = "master" }
capstone = { git = "https://github.com/oblivia-simplex/capstone-rs", branch = "master" }
elf      = "0.0.10"
byteorder = "0.5.3"
pcre = "0.2.3"
bitflags = "0.7.0"
rand = "0.3.0"
